### ISSUE TITLE
Create generic input for all the supported quantum chemistry packages 

### ISSUE THREAD

**Issue by felipeZ** [votca/xtp#318]
Currently the input to run a DFT calculation with any of the supported quantum chemistry packages (**Orca**, **NwChem**, **Gaussian** or **XTP**) must be manually specified.
A new general syntax should be provided to represent all the input. This expressions are subsequently translated to the corresponding quantum package syntax.
For example:
```
settings.basis = ubecppol
settings.gw_basis = aux-ubecppol
settings.functional = PBE 
settings.charge = 0
```

**Comment by felipeZ** [comment]
The YAML format seems a better idea:
```yml
settings:
  basis:
    ubecppol
  functional:
    PBE0  
  threads:
    8  
  charge:
    0
  scratch:
    "/tmp"
```
